include: 
  - project: my-work9690247/devops/ci-templates
    ref: main
    file:
      - build-template.yml
      - deploy-with-compose-template.yml

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        ENV_NAME: "production"
    - when: never

stages:
  - build
  - deploy

build_app:
  extends: .build-template
  tags:
    - shared
    - dind
  variables:
    IMAGE_TAG: "$ENV_NAME"

build_cron:
  extends: .build-template
  tags:
    - shared
    - dind
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE/cron"
    IMAGE_TAG: "$ENV_NAME"
    DOCKERFILE_PATH: cron.Dockerfile

deploy:
  extends: .deploy-compose-template
  variables:
    DC_IMAGE_NAME: "$CI_REGISTRY_IMAGE"
    DC_IMAGE_TAG: "$ENV_NAME"
    DC_APP_PORT: "$DEPLOYMENT_APP_PORT"
    DC_CRON_IMAGE_NAME: "$CI_REGISTRY_IMAGE/cron"
    DC_CRON_IMAGE_TAG: "$ENV_NAME"
    DEPLOYMENT_SERVER_HOST: "$DEPLOYMENT_HOST"
    APP_DOTENV_FILE: "$APP_DOTENV"
    
