services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    restart: unless-stopped
    ports:
      - 8082:80
    env_file:
      - path: ./.env
        required: false
    volumes:
      - bot_storage:/var/www/storage
      - bot_base:/var/www/database

volumes:
  bot_storage:
  bot_base:
