name: Build Template

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: "Dockerfile"
      build_context:
        required: false
        type: string
        default: "."

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    env:
      IMAGE_NAME: ${{ github.event.repository.name }}
      PIPELINE_IID: ${{ github.run_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          set -e
          IMAGE_REPO="${{ vars.CONTAINER_REGISTRY }}/${{ secrets.CONTAINER_REGISTRY_USER }}/$IMAGE_NAME"
          DOCKER_BUILDKIT=1 docker build -f ${{ inputs.dockerfile_path }} -t ${IMAGE_REPO}:$PIPELINE_IID ${{ inputs.build_context }}
          docker tag ${IMAGE_REPO}:$PIPELINE_IID ${IMAGE_REPO}:${{ inputs.image_tag }}
          docker push ${IMAGE_REPO}:$PIPELINE_IID
          docker push ${IMAGE_REPO}:${{ inputs.image_tag }}