name: Deploy Template

on:
  workflow_call:
    inputs:
      env_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    environment: ${{ inputs.env_name }}
    container:
      image: xursanov/dind:v1
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      options: --user root
    env:
      DC_IMAGE_NAME: "${{ vars.CONTAINER_REGISTRY }}/${{ secrets.CONTAINER_REGISTRY_USER }}/$IMAGE_NAME"
      DC_IMAGE_TAG: ${{ inputs.env_name }}
      DC_APP_PORT: ${{ vars.DEPLOYMENT_APP_PORT }}
      COMPOSE_PROJECT_NAME: ${{ github.event.repository.name }}
      COMPOSE_FILE_DEST: /home/deployer/${{ github.event.repository.name }}/docker-compose.yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYER_SSH_PRIVATE_KEY }}" > ~/.ssh/deployer_key
          chmod 600 ~/.ssh/deployer_key

      - name: Substitute variables in docker-compose
        run: envsubst < ./docker-compose.yml | sponge ./docker-compose.yml

      - name: Echo variable for test
        run: cat ~/.ssh/deployer_key

      - name: Transfer docker-compose file
        run: |
          rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deployer_key" \
            --rsync-path="mkdir -p $(dirname $COMPOSE_FILE_DEST) && rsync" \
            ./docker-compose.yml \
            deployer@${{ vars.DEPLOYMENT_HOST }}:$COMPOSE_FILE_DEST

      - name: Transfer .env file
        run: |
          echo "${{ secrets.APP_DOTENV }}" > /tmp/app.env
          rsync -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deployer_key" \
            /tmp/app.env \
            deployer@${{ vars.DEPLOYMENT_HOST }}:$(dirname $COMPOSE_FILE_DEST)/.env
          rm /tmp/app.env

      - name: Deploy on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deployer_key \
            deployer@${{ vars.DEPLOYMENT_HOST }} "
            set -e &&
            export COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME &&
            docker login -u ${{ secrets.CONTAINER_REGISTRY_USER }} -p ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} ${{ vars.CONTAINER_REGISTRY }} &&
            docker compose -f $COMPOSE_FILE_DEST pull &&
            docker compose -f $COMPOSE_FILE_DEST up --force-recreate --remove-orphans -d &&
            docker image prune -f"

      - name: Cleanup SSH key
        if: always()
        run: rm -f ~/.ssh/deployer_key
